### ISSUE TITLE
Batch import .so files failed

### ISSUE THREAD

**Issue by Hao17** [Ayrx/ghidra_utils#19]
```java
int org.objectweb.asm.MethodWriter.getSize()'
java.lang.NoSuchMethodError: 'int org.objectweb.asm.MethodWriter.getSize()'
	at org.objectweb.asm.AsmBridge.sizeOfMethodWriter(AsmBridge.java:28)
	at com.googlecode.d2j.dex.ExDex2Asm.convertCode(ExDex2Asm.java:55)
	at com.googlecode.d2j.dex.Dex2Asm.convertMethod(Dex2Asm.java:509)
	at com.googlecode.d2j.dex.Dex2Asm.convertClass(Dex2Asm.java:406)
	at com.googlecode.d2j.dex.Dex2Asm.convertDex(Dex2Asm.java:422)
	at ghidra.file.formats.android.dex.DexToJarFileSystem.lambda$getJarFile$1(DexToJarFileSystem.java:139)
	at ghidra.formats.gfilesystem.FileSystemService.getDerivedByteProviderPush(FileSystemService.java:487)
	at ghidra.file.formats.android.dex.DexToJarFileSystem.getJarFile(DexToJarFileSystem.java:83)
	at ghidra.file.formats.android.dex.DexToJarFileSystem.open(DexToJarFileSystem.java:156)
	at ghidra.formats.gfilesystem.factory.GFileSystemBaseFactory.create(GFileSystemBaseFactory.java:91)
	at ghidra.formats.gfilesystem.factory.GFileSystemBaseFactory.create(GFileSystemBaseFactory.java:40)
	at ghidra.formats.gfilesystem.factory.FileSystemFactoryMgr.mountUsingFactory(FileSystemFactoryMgr.java:176)
	at ghidra.formats.gfilesystem.factory.FileSystemFactoryMgr.probe(FileSystemFactoryMgr.java:337)
	at ghidra.formats.gfilesystem.FileSystemService.probeFileForFilesystem(FileSystemService.java:731)
	at ghidra.formats.gfilesystem.FileSystemService.probeFileForFilesystem(FileSystemService.java:682)
	at ghidra.plugins.importer.batch.BatchInfo.processAsFS(BatchInfo.java:303)
	at ghidra.plugins.importer.batch.BatchInfo.doAddFile(BatchInfo.java:229)
	at ghidra.plugins.importer.batch.BatchInfo.processFS(BatchInfo.java:350)
	at ghidra.plugins.importer.batch.BatchInfo.processAsFS(BatchInfo.java:318)
	at ghidra.plugins.importer.batch.BatchInfo.doAddFile(BatchInfo.java:229)
	at ghidra.plugins.importer.batch.BatchInfo.processFS(BatchInfo.java:350)
	at ghidra.plugins.importer.batch.BatchInfo.doAddFile(BatchInfo.java:225)
	at ghidra.plugins.importer.batch.BatchInfo.addFile(BatchInfo.java:197)
	at ghidra.plugins.importer.batch.BatchInfo.doAddFiles(BatchInfo.java:503)
	at ghidra.plugins.importer.batch.BatchInfo$AddFilesRunnable.monitoredRun(BatchInfo.java:542)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:306)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Hao17** [comment]
```
Build Date: 2022-Nov-15 1249 EST
Ghidra Version: 10.2.2
Java Home: /opt/homebrew/Cellar/openjdk@17/17.0.6/libexec/openjdk.jdk/Contents/Home
JVM Version: Homebrew 17.0.6
OS: Mac OS X 13.1 aarch64
```
